### ISSUE TITLE
History Page Render Error

### ISSUE THREAD

**Issue by kwangmeng** [celer-network/layer2-finance-bugs#1]
Hi, I'm experiencing this issue, when I route to /history page. 

Steps to reproduce: 
1. Claim faucets test token 
2. Deposit CELR to L2
3. Upon deposited, withdraw CELR to L1, 
4. Go to history page, will show error. 

![Screenshot 2021-04-06 at 12 20 13 PM](https://user-images.githubusercontent.com/21683078/113659448-9ca19380-96d4-11eb-8f56-3b34114c8dcb.png)

**Comment by Dominator008** [comment]
Thanks for the report. Can you check if it's fixed now?

**Comment by kwangmeng** [comment]
@Dominator008 , the issue seems resolved. Im closing this now. Thanks alot.
