### ISSUE TITLE
Next aggregated fund reallocation timer resets to previous state

### ISSUE THREAD

**Issue by kwangmeng** [celer-network/layer2-finance-bugs#2]
Hi, I noticed that the timer auto resets to previous state if I toggle between different tokens. 

I not sure is this the real feature or a timer condition bug ? 

Thanks

https://user-images.githubusercontent.com/21683078/113803450-27df5f80-978f-11eb-8656-0228fd305161.mov

**Comment by kwangmeng** [comment]
closing this issue, found the web has already resolved this issue

**Comment by Dominator008** [comment]
Thanks for the report. Note that the countdown is only shown as a rough estimate of when the next batch of fund allocation will happen, so don't rely on it :)
