### ISSUE TITLE
History Page, Layer2 Strategy Transactions Table Page Limit View Issue

### ISSUE THREAD

**Issue by kwangmeng** [celer-network/layer2-finance-bugs#3]
Hi, 

Found out that the table page limit view is not working, when selecting other limits. Please refer to the snapshot below. 

Thanks

https://user-images.githubusercontent.com/21683078/113956054-78b68d00-984f-11eb-9e11-f757ed66bfb4.mov

**Comment by Dominator008** [comment]
Ack. This is being worked on.

**Comment by kwangmeng** [comment]
Cool, thanks for being so responsive!
