### ISSUE TITLE
how to query strategy address

### ISSUE THREAD

**Issue by gasolin** [celer-network/layer2-finance-bugs#4]
making a site https://ethhole.link/ to track token flow from ethereum to Layer2 / Sidechain

Due to Layer2.Finance's characteristic, the main address's token balance will flow to other DEFI periodically,
therefore to correctly collect the Layer2.Finance TVL

1. not only need tracking the main address, but also need to track strategies TVL
2. or call `strategiesBalance` provide by https://etherscan.io/address/0xf86fd6735f88d5b6aa709b357ad5be22cedf1a05#readContract

the 2nd way can pass the index and get the balance, but not obvious about how the index maping to which strategy

so it will be helpful if you can list the `index: strategy address` mapping somewhere

some issue for l2beat TVL

**Comment by Dominator008** [comment]
https://etherscan.io/address/0xFe81ab6930A30BdaE731fe7b6C6ABFbEAFc014a8#readContract. Check out `strategyIndexToAddress`.

**Comment by gasolin** [comment]
thanks, that's what I need
